#server:
  #port: 8080
#spring:
 # application:
 #   name: config-server
 # cloud:
  #  config:
  #    server:
  #      git:
  #        uri: https://github.com/hudadada/SpringcloudConfig/config
  #        username: huguoyu
   #       password: GY123.**