eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8780
spring:
  application:
    name: service-solr
  data:
    solr:
      host: http://localhost:8888/solr

